<?php

namespace SimBundle\Repository;

/**
 * RecomendacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecomendacionRepository extends \Doctrine\ORM\EntityRepository
{
}
